// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CPNettySocket.Msg.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN



@class Head;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - CpnettySocketMsgRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface SWNettySocketMsgRoot : GPBRootObject
@end

#pragma mark - Msg

typedef GPB_ENUM(Msg_FieldNumber) {
  Msg_FieldNumber_Head = 1,
  Msg_FieldNumber_Body = 2,
};

@interface Msg : GPBMessage

/** 消息头 */
@property(nonatomic, readwrite, strong, null_resettable) Head *head;
/** Test to see if @c head has been set. */
@property(nonatomic, readwrite) BOOL hasHead;

/** 消息体 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *body;

@end

#pragma mark - Head

typedef GPB_ENUM(Head_FieldNumber) {
  Head_FieldNumber_MsgId = 1,
  Head_FieldNumber_MsgType = 2,
  Head_FieldNumber_MsgContentType = 3,
  Head_FieldNumber_FromId = 4,
  Head_FieldNumber_ToId = 5,
  Head_FieldNumber_Timestamp = 6,
  Head_FieldNumber_StatusReport = 7,
  Head_FieldNumber_Extend = 8,
};

@interface Head : GPBMessage

/** 消息id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msgId;

/** 消息类型  1001：握手消息；1002：心跳消息； 2001：私聊消息；  2002：群发消息； 3001:新增好友-验证消息   1009：确认客户端收到消息结果 */
@property(nonatomic, readwrite) int32_t msgType;

/** 消息内容类型  1 文字  2 图片  3 音文件 4 短视频文件  5 个人明信片 6 消息撤回  7  位置消息  8 文件  9 贴图   10 消息双向删除  11 变更群名称  12 群新加入提示信息 13 群成员退出提示信息 14 群禁言 15 群禁止加好友 16 群主转让  17群踢成员   18 新好友提示信息 */
@property(nonatomic, readwrite) int32_t msgContentType;

/** 消息发送者id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *fromId;

/** 消息接收者id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *toId;

/** 消息时间戳 */
@property(nonatomic, readwrite) int64_t timestamp;

/** 状态报告      0 成功 ， -1 失败 ， 1 成功-消息内容有变化(存在敏感词)， -2  失败（用户登录token失效），-3 被对方拉黑 ， -4 被对方删除 ， -5 不是群成员呢  ，-6 群禁言 ， -7未添加对方好友 */
@property(nonatomic, readwrite) int32_t statusReport;

/** 扩展字段，以key/value形式存放的json.{“id”:"asdasds","token":"sdasdasdas"}    token：用户鉴权  messageId：客户端消息ID   gmID：被踢群成员用户ID  */
/// token 用户鉴权 ， messageId 客户端消息ID  ， gmID:被踢群成员用户ID   ，gmNewID:新建群/新加入成员用户ID
/// verMsgID:新好友-验证消息ID ，newFriVerMsg:新好友-验证消息内容 ,memberType：用户类型（1：普通用户，2：客服助手）
@property(nonatomic, readwrite, copy, null_resettable) NSString *extend;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
